<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8" />
    <title>{% block page_title %}Metronic | Login Page{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="{% block page_description %}{% endblock %}" name="description" />
    <meta content="{% block page_author %}{% endblock %}" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    {{ stylesheet_link("css/bootstrap.min.css") }}
    {{ stylesheet_link("css/bootstrap-responsive.min.css") }}
    {{ stylesheet_link("css/font-awesome.min.css") }}
    {{ stylesheet_link("css/style-metro.css") }}
    {{ stylesheet_link("css/style.css") }}
    {{ stylesheet_link("css/style-responsive.css") }}
    {{ stylesheet_link("css/default.css") }}
    {{ stylesheet_link("css/uniform.default.css") }}
    <!-- END GLOBAL MANDATORY STYLES -->
    {% block page_level_styles %}
    <!-- BEGIN PAGE LEVEL STYLES -->
    {{ stylesheet_link("css/login.css") }}
    <!-- END PAGE LEVEL STYLES -->
    {% endblock %}
    <link rel="shortcut icon" href="/image/favicon.ico" />
</head>
<!-- END HEAD -->
{% block page_content %}
{{ content() }}
{% endblock %}
{% block copyright %}
<!-- BEGIN COPYRIGHT -->
<div class="copyright">
    2013 &copy; Metronic. Admin Dashboard Template.
</div>
<!-- END COPYRIGHT -->
{% endblock %}
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
{{ javascript_include("js/jquery-1.10.1.min.js") }}
{{ javascript_include("js/jquery-migrate-1.2.1.min.js") }}
{{ javascript_include("js/jquery-ui-1.10.1.custom.min.js") }}
{{ javascript_include("js/bootstrap.min.js") }}
<!--[if lt IE 9]>
{{ javascript_include("js/excanvas.min.js") }}
{{ javascript_include("js/respond.min.js") }}
<![endif]-->
{{ javascript_include("js/jquery.slimscroll.min.js") }}
{{ javascript_include("js/jquery.blockui.min.js") }}
{{ javascript_include("js/jquery.cookie.min.js") }}
{{ javascript_include("js/jquery.uniform.min.js") }}
<!-- END CORE PLUGINS -->

{% block page_level_scripts %}
<!-- BEGIN PAGE LEVEL PLUGINS -->
{{ javascript_include("js/jquery.validate.min.js") }}
<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN PAGE LEVEL SCRIPTS -->
{{ javascript_include("js/app.js") }}
{{ javascript_include("js/login.js") }}
<!-- END PAGE LEVEL SCRIPTS -->
<script>
    jQuery(document).ready(function() {
        App.init();
        Login.init();
    });
</script>
<!-- END JAVASCRIPTS -->
{% endblock %}
</body>
<!-- END BODY -->
</html>